/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginPreviewRouteImport } from './routes/login-preview'
import { Route as ConnectPreviewRouteImport } from './routes/connect-preview'
import { Route as AppPreviewRouteImport } from './routes/app-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPreviewIndexRouteImport } from './routes/app-preview.index'
import { Route as AppPreviewSupportRouteImport } from './routes/app-preview.support'
import { Route as AppPreviewSubscriptionRouteImport } from './routes/app-preview.subscription'
import { Route as AppPreviewReferralsRouteImport } from './routes/app-preview.referrals'
import { Route as AppPreviewPaymentsRouteImport } from './routes/app-preview.payments'
import { Route as AppPreviewDevicesRouteImport } from './routes/app-preview.devices'
import { Route as AppPreviewDashboardRouteImport } from './routes/app-preview.dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPreviewRoute = LoginPreviewRouteImport.update({
  id: '/login-preview',
  path: '/login-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectPreviewRoute = ConnectPreviewRouteImport.update({
  id: '/connect-preview',
  path: '/connect-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/app-preview',
  path: '/app-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewIndexRoute = AppPreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewSupportRoute = AppPreviewSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewSubscriptionRoute = AppPreviewSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewReferralsRoute = AppPreviewReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewPaymentsRoute = AppPreviewPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewDevicesRoute = AppPreviewDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppPreviewRoute,
} as any)
const AppPreviewDashboardRoute = AppPreviewDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppPreviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRouteWithChildren
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app-preview/dashboard': typeof AppPreviewDashboardRoute
  '/app-preview/devices': typeof AppPreviewDevicesRoute
  '/app-preview/payments': typeof AppPreviewPaymentsRoute
  '/app-preview/referrals': typeof AppPreviewReferralsRoute
  '/app-preview/subscription': typeof AppPreviewSubscriptionRoute
  '/app-preview/support': typeof AppPreviewSupportRoute
  '/app-preview/': typeof AppPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app-preview/dashboard': typeof AppPreviewDashboardRoute
  '/app-preview/devices': typeof AppPreviewDevicesRoute
  '/app-preview/payments': typeof AppPreviewPaymentsRoute
  '/app-preview/referrals': typeof AppPreviewReferralsRoute
  '/app-preview/subscription': typeof AppPreviewSubscriptionRoute
  '/app-preview/support': typeof AppPreviewSupportRoute
  '/app-preview': typeof AppPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-preview': typeof AppPreviewRouteWithChildren
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app-preview/dashboard': typeof AppPreviewDashboardRoute
  '/app-preview/devices': typeof AppPreviewDevicesRoute
  '/app-preview/payments': typeof AppPreviewPaymentsRoute
  '/app-preview/referrals': typeof AppPreviewReferralsRoute
  '/app-preview/subscription': typeof AppPreviewSubscriptionRoute
  '/app-preview/support': typeof AppPreviewSupportRoute
  '/app-preview/': typeof AppPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-preview'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
    | '/app-preview/dashboard'
    | '/app-preview/devices'
    | '/app-preview/payments'
    | '/app-preview/referrals'
    | '/app-preview/subscription'
    | '/app-preview/support'
    | '/app-preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
    | '/app-preview/dashboard'
    | '/app-preview/devices'
    | '/app-preview/payments'
    | '/app-preview/referrals'
    | '/app-preview/subscription'
    | '/app-preview/support'
    | '/app-preview'
  id:
    | '__root__'
    | '/'
    | '/app-preview'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
    | '/app-preview/dashboard'
    | '/app-preview/devices'
    | '/app-preview/payments'
    | '/app-preview/referrals'
    | '/app-preview/subscription'
    | '/app-preview/support'
    | '/app-preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppPreviewRoute: typeof AppPreviewRouteWithChildren
  ConnectPreviewRoute: typeof ConnectPreviewRoute
  LoginPreviewRoute: typeof LoginPreviewRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-preview': {
      id: '/login-preview'
      path: '/login-preview'
      fullPath: '/login-preview'
      preLoaderRoute: typeof LoginPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-preview': {
      id: '/connect-preview'
      path: '/connect-preview'
      fullPath: '/connect-preview'
      preLoaderRoute: typeof ConnectPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-preview': {
      id: '/app-preview'
      path: '/app-preview'
      fullPath: '/app-preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-preview/': {
      id: '/app-preview/'
      path: '/'
      fullPath: '/app-preview/'
      preLoaderRoute: typeof AppPreviewIndexRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/support': {
      id: '/app-preview/support'
      path: '/support'
      fullPath: '/app-preview/support'
      preLoaderRoute: typeof AppPreviewSupportRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/subscription': {
      id: '/app-preview/subscription'
      path: '/subscription'
      fullPath: '/app-preview/subscription'
      preLoaderRoute: typeof AppPreviewSubscriptionRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/referrals': {
      id: '/app-preview/referrals'
      path: '/referrals'
      fullPath: '/app-preview/referrals'
      preLoaderRoute: typeof AppPreviewReferralsRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/payments': {
      id: '/app-preview/payments'
      path: '/payments'
      fullPath: '/app-preview/payments'
      preLoaderRoute: typeof AppPreviewPaymentsRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/devices': {
      id: '/app-preview/devices'
      path: '/devices'
      fullPath: '/app-preview/devices'
      preLoaderRoute: typeof AppPreviewDevicesRouteImport
      parentRoute: typeof AppPreviewRoute
    }
    '/app-preview/dashboard': {
      id: '/app-preview/dashboard'
      path: '/dashboard'
      fullPath: '/app-preview/dashboard'
      preLoaderRoute: typeof AppPreviewDashboardRouteImport
      parentRoute: typeof AppPreviewRoute
    }
  }
}

interface AppPreviewRouteChildren {
  AppPreviewDashboardRoute: typeof AppPreviewDashboardRoute
  AppPreviewDevicesRoute: typeof AppPreviewDevicesRoute
  AppPreviewPaymentsRoute: typeof AppPreviewPaymentsRoute
  AppPreviewReferralsRoute: typeof AppPreviewReferralsRoute
  AppPreviewSubscriptionRoute: typeof AppPreviewSubscriptionRoute
  AppPreviewSupportRoute: typeof AppPreviewSupportRoute
  AppPreviewIndexRoute: typeof AppPreviewIndexRoute
}

const AppPreviewRouteChildren: AppPreviewRouteChildren = {
  AppPreviewDashboardRoute: AppPreviewDashboardRoute,
  AppPreviewDevicesRoute: AppPreviewDevicesRoute,
  AppPreviewPaymentsRoute: AppPreviewPaymentsRoute,
  AppPreviewReferralsRoute: AppPreviewReferralsRoute,
  AppPreviewSubscriptionRoute: AppPreviewSubscriptionRoute,
  AppPreviewSupportRoute: AppPreviewSupportRoute,
  AppPreviewIndexRoute: AppPreviewIndexRoute,
}

const AppPreviewRouteWithChildren = AppPreviewRoute._addFileChildren(
  AppPreviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppPreviewRoute: AppPreviewRouteWithChildren,
  ConnectPreviewRoute: ConnectPreviewRoute,
  LoginPreviewRoute: LoginPreviewRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
