/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginPreviewRouteImport } from './routes/login-preview'
import { Route as ConnectPreviewRouteImport } from './routes/connect-preview'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPreviewRoute = LoginPreviewRouteImport.update({
  id: '/login-preview',
  path: '/login-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectPreviewRoute = ConnectPreviewRouteImport.update({
  id: '/connect-preview',
  path: '/connect-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-preview': typeof ConnectPreviewRoute
  '/login-preview': typeof LoginPreviewRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/connect-preview'
    | '/login-preview'
    | '/offer'
    | '/privacy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectPreviewRoute: typeof ConnectPreviewRoute
  LoginPreviewRoute: typeof LoginPreviewRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-preview': {
      id: '/login-preview'
      path: '/login-preview'
      fullPath: '/login-preview'
      preLoaderRoute: typeof LoginPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-preview': {
      id: '/connect-preview'
      path: '/connect-preview'
      fullPath: '/connect-preview'
      preLoaderRoute: typeof ConnectPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectPreviewRoute: ConnectPreviewRoute,
  LoginPreviewRoute: LoginPreviewRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
